const fs = require('fs');

const statuses = ['Draft', 'Quotation Sent', 'Awaiting Approval', 'Approved', 'Material Reserved', 'Production Assigned', 'Knitting', 'Dyeing', 'Compacting', 'Cutting', 'Printing', 'Embroidery', 'Stitching', 'Quality Check', 'Packing', 'Dispatch Ready', 'Dispatched', 'Delivered', 'Closed'];

function randInt(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function randArr(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function escapeSql(str) { return str.replace(/'/g, "''"); }

let sql = `-- Expanded Mock Data Generated by Script\n\n`;
sql += `DELETE FROM transactions;\nDELETE FROM orders;\nDELETE FROM inventory;\nDELETE FROM customers;\n\n`;

// Generate Customers
for(let i=10; i<=30; i++) {
    const id = `c-0${i}`;
    const name = randArr(['Rahul Sharma', 'Ankit Desai', 'Priya Kapoor', 'Neha Singh', 'Vikram Aditya', 'Amit Patel', 'Sonia Gupta']);
    const company = randArr(['Reliance Trends', 'Myntra', 'Lifestyle', 'Shoppers Stop', 'Max Fashion', 'Westside', 'Pantaloons', 'Zudio']) + ' ' + randInt(1,99);
    const initials = name.split(' ').map(n=>n[0]).join('');
    
    sql += `INSERT INTO customers (id, name, company, initials, email, phone, status, statusColor) VALUES ('${id}', '${escapeSql(name)}', '${escapeSql(company)}', '${initials}', 'contact${i}@example.com', '+91 98765432${i}', 'Active', 'bg-[#008A00]/10 text-[#008A00]');\n`;
}

// Generate Inventory
const fabrics = ['Cotton', 'Polyester', 'Linen', 'Silk', 'Denim', 'Fleece', 'Nylon', 'Rayon', 'Spandex'];
for(let i=10; i<=30; i++) {
    const id = `inv-0${i}`;
    const name = randArr(['Premium ', 'Organic ', 'Recycled ', 'Standard ']) + randArr(fabrics) + ' ' + randArr(['Jersey', 'Knit', 'Woven', 'Twill', 'Blend']);
    const sku = `FAB-${randInt(100,999)}`;
    const qty = randInt(100, 10000);
    const unit = randArr(['Meters', 'Yards', 'Kg', 'Rolls']);
    const status = qty < 500 ? 'Low Stock' : 'In Stock';
    const color = qty < 500 ? 'bg-error/10 text-error' : 'bg-[#008A00]/10 text-[#008A00]';
    
    sql += `INSERT INTO inventory (id, name, sku, quantity, unit, status, statusColor, icon, iconColor, historicalAvgConsumption) VALUES ('${id}', '${escapeSql(name)}', '${sku}', ${qty}, '${unit}', '${status}', '${color}', 'inventory_2', 'bg-primary/10 text-primary', ${randInt(1, 5) + (randInt(0,9)/10)});\n`;
}

// Generate Orders
for(let i=10; i<=40; i++) {
    const id = `ORD-${randInt(1000, 9999)}`;
    const customerId = `c-0${randInt(10,30)}`;
    const product = randArr(['Basic Tees', 'Polo Shirts', 'Denim Jackets', 'Chinos', 'Hoodies', 'Sweatshirts', 'Activewear Shorts']);
    const qty = randInt(500, 15000);
    const price = randInt(150, 1500) + .50;
    const subtotal = qty * price;
    const tax = subtotal * 0.05;
    const grandTotal = subtotal + tax;
    const incurredCost = subtotal * (randInt(40, 70) / 100);
    
    const status = randArr(statuses);
    const day = randInt(1, 11);
    
    sql += `INSERT INTO orders (id, customerId, product, qty, unitPrice, subtotal, discount, tax, shipping, grandTotal, value, incurredCost, quotedCost, status, statusColor, dateMonth, dateDay, deliveryDate, priority, progressPercentage, progressLabel, progressColor, paymentStatus) VALUES ('${id}', '${customerId}', '${escapeSql(product)}', ${qty}, ${price}, ${subtotal}, 0, ${tax}, 0, ${grandTotal}, ${grandTotal}, ${incurredCost}, ${grandTotal}, '${status}', 'bg-surface-variant text-secondary', 'Sep', '${day}', '2026-09-${day + randInt(5, 10)}', '${randArr(['High', 'Normal', 'Low'])}', ${randInt(10,90)}, '${status}', 'bg-primary', '${randArr(['Paid', 'Partial', 'Unpaid'])}');\n`;
}

// Generate Transactions
const tTypes = ['Income', 'Expense', 'Payment'];
for(let i=100; i<=150; i++) {
    const id = `txn-${i}`;
    const type = randArr(tTypes);
    const amount = randInt(1000, 500000);
    const isNeg = type === 'Expense' ? 1 : 0;
    const day = randInt(1, 11).toString().padStart(2, '0');
    
    sql += `INSERT INTO transactions (id, type, title, category, amount, isNegative, date) VALUES ('${id}', '${type}', '${type} Record ${i}', 'General', ${amount}, ${isNeg}, '2026-09-${day}');\n`;
}

fs.writeFileSync('backend/seed_expanded.sql', sql);
console.log('done');
