-- Seed data for Garment OS D1
-- Mirrors mockData.js

INSERT OR IGNORE INTO customers (id, name, company, initials, avatar, email, phone, status, statusColor) VALUES
('c-001', 'Priya Rajan', 'Chennai Silks', 'PR', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjsQrnDGH6EpdDe4Jzpub5fpI9paxS1qSAF-0EYDdMRn-40Zfp1H4ivFc2T7cTj7HS3uZnWtjlCmyhcGKN0KHS3HNaNzMWa9yB-DqA66rQK9arPwIXmP6fDsjao2TRWu0oBpTuJXOMi1KOYpAZUIu7lItqa1jt8lggfNjZcOdLiLUjAY1Pzb1YSCbv0Mv1uuofmOTAuRcPT0in4vDp1x6znmYUJiKEFUrz6dxdh7LMj1KSq02cN5HiRB1n2brh4gxTAT1U9qJlUa8Q', 'priya@chennaisilks.com', '+1 (555) 019-2834', 'Active', 'bg-[#008A00]/10 text-[#008A00]'),
('c-002', 'Karthik Natarajan', 'Arvind Fashions', 'KN', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnM486kZM-lpNWk2IlqpzF64WxPwyZNAGRmmwbnl1hZ-4jogabI--2ibQdvzPZRfGgcdsRhOwmJc4blIdV_dfrApDpiQ-m6C8uPLmMUb6vUjeCvEyruI55DlXQUPPUz4Wbk722E-G5pUrRRZHOpe912RqyxaxQseAPz4miWYpvNJHYJShsMaEi7ViP2m5_Hc5EXSnMakPPbSQ45nQQTAYQ5l5gwT6clchpVQxqZCiAOfsBJ5hzqwoaHDLdD-YRAA1JFY8S7YOnN_ON', 'k.natarajan@arvind.com', '+1 (555) 018-9273', 'Inactive', 'bg-surface-variant text-secondary');

INSERT OR IGNORE INTO costings (id, styleRef, clientId, totalUnitCost, retailPrice, status, date, materials) VALUES
('cost-001', 'SS24-TS-01', 'c-001', 22.10, 34.50, 'Draft', '2026-07-15', '[{"invId":"inv-001","estimatedConsumption":1.2}]');

INSERT OR IGNORE INTO orders (id, customerName, customerId, costingId, product, sizes, colours, qty, unitPrice, subtotal, discount, tax, shipping, grandTotal, value, incurredCost, quotedCost, status, statusColor, dateMonth, dateDay, deliveryDate, priority, factory, productionManager, merchandiser, progressPercentage, progressLabel, progressColor, notes, timeline, tasks, expenses, paymentStatus, paymentReceived, fabric, activityLog) VALUES
('ORD-992', 'Chennai Silks', 'c-001', 'cost-001', 'Organic Cotton Tees (SS24)', '["S","M","L","XL"]', '["Navy","White","Heather Grey"]', 5000, 34.50, 172500, 0, 8625, 500, 181625, 181625, 4500, 110500, 'Cutting', 'bg-orange-500/10 text-orange-600', 'Oct', '24', '2026-10-24', 'High', 'Unit A - South Wing', 'Meenakshi Iyer', 'Ramesh Krishnan', 45, 'Cutting Patterns', 'bg-orange-500', 'Strict QC needed on Navy colorway.', '[{"date":"Oct 20, 2026 - 09:00 AM","title":"Order Created","user":"Priya Rajan","type":"system","status":"completed"},{"date":"Oct 21, 2026 - 10:15 AM","title":"Status Updated: Approved","user":"System","type":"status","status":"completed"},{"date":"Oct 22, 2026 - 11:30 AM","title":"Status Updated: Material Reserved","user":"Inventory","type":"inventory","status":"completed"},{"date":"Oct 24, 2026 - 08:00 AM","title":"Status Updated: Cutting","user":"Meenakshi Iyer","type":"status","status":"active"}]', '[{"id":"t1","title":"Source 500kg Organic Cotton Yarn","assignee":"Purchasing","status":"Completed"},{"id":"t2","title":"Cut patterns for sizes S, M, L","assignee":"Cutting Floor","status":"Pending"},{"id":"t3","title":"QC on first 100 cut pieces","assignee":"QC Team","status":"Pending"}]', '[{"id":"e1","type":"Material","amount":4000,"date":"2026-10-22","notes":"Cotton Yarn Purchase"},{"id":"e2","type":"Overhead","amount":500,"date":"2026-10-23","notes":"Cutting Setup"}]', 'Partial', 50000, '100% Organic Cotton Jersey', '[{"note":"Client confirmed Navy colorway. Strict QC needed.","user":"Priya Rajan","date":"Oct 21, 2026 - 10:30 AM"}]');

INSERT OR IGNORE INTO inventory (id, name, sku, quantity, unit, status, statusColor, icon, iconColor, historicalAvgConsumption) VALUES
('inv-001', 'Organic Cotton Jersey', 'FAB-OC-001', 4500, 'Meters', 'In Stock', 'bg-[#008A00]/10 text-[#008A00]', 'inventory_2', 'bg-primary/10 text-primary', 1.25),
('inv-002', 'Navy Blue Thread', 'THR-NB-024', 12, 'Cones', 'Low Stock', 'bg-error/10 text-error', 'linear_scale', 'bg-[#5E5CE6]/10 text-[#5E5CE6]', 0.05);

INSERT OR IGNORE INTO batches (id, orderId, description, phase, progress, progressColor, expenses, consumptions) VALUES
('B-8092', 'ORD-992', 'Organic Tees • 5k units', 'Cutting', 45, 'bg-primary', '["txn-004"]', '[{"invId":"inv-001","actualConsumption":150,"date":"2026-10-15"}]');
